/// Maps TMDB keyword ids → extra genre names to union into a title's
/// `genres` set.
///
/// The problem this solves: genre filtering on Home + Decide is an AND
/// intersection (`selected.every(r.genres.contains)`). TMDB's canonical
/// genre taxonomy is narrow — e.g. "Firefly" is tagged `Sci-Fi & Fantasy`
/// only, not `Western`, so a Western + Sci-Fi filter drops it. TMDB's
/// keyword taxonomy is much richer (thousands of tags), so a keyword like
/// "space western" is a reliable signal that a title also deserves the
/// `Western` tag for intersection purposes.
///
/// **Scope**: this is additive only. We never remove canonical genres based
/// on keywords — a title that's canonically a Comedy stays a Comedy even
/// if a keyword says otherwise. The map only widens.
///
/// **Populating the map**: TMDB keyword ids are stable but not publicly
/// documented in bulk. Use `scripts/generate_keyword_genre_map.py` to look
/// up ids by name and emit entries. Each entry should be a keyword that
/// implies ≥1 canonical genre with high confidence (e.g. "cyberpunk" →
/// Science Fiction is safe; "based on novel" → no genre implication and
/// should NOT be in the map).
///
/// Keys are TMDB keyword ids; values are sets of canonical genre names
/// matching those in `utils/tmdb_genres.dart`. Unknown genre names are
/// harmless — `augmentGenresWithKeywords` just unions them in.
/// Bump when [kKeywordToExtraGenres] gains meaningful new entries that should
/// re-augment previously-fetched rec docs. Rec docs store the version that
/// was live when they were last augmented; the service re-fetches keywords
/// (and re-runs augmentation) whenever the stored version is older than this.
const int kKeywordsVersion = 2;

const Map<int, Set<String>> kKeywordToExtraGenres = <int, Set<String>>{
  // ---- seed entries (pre-generator, kept for sanity / back-compat) ----
  9951: {'Science Fiction'}, // alien
  4458: {'Science Fiction'}, // post-apocalyptic future
  4565: {'Science Fiction'}, // dystopia
  10084: {'Animation'}, // anime
  9715: {'Action'}, // superhero
  // 1721 "fight" — intentionally NOT here; too broad, would over-tag dramas.

  // ---- generated by scripts/generate_keyword_genre_map.py ----
  // Cross-genre sci-fi/war (the Sci-Fi + War zero-result problem).
  1826: {'Science Fiction', 'War'}, // space marine
  14909: {'Science Fiction', 'War'}, // alien invasion
  2902: {'Science Fiction', 'War'}, // space battle
  161176: {'Science Fiction'}, // space opera
  // Western crossovers.
  11606: {'Science Fiction', 'Western'}, // space western
  168713: {'Western'}, // neo-western
  // Horror subgenres.
  12339: {'Horror'}, // slasher
  163053: {'Horror'}, // found footage
  215959: {'Horror', 'Science Fiction'}, // cosmic horror
  283085: {'Horror'}, // body horror
  295907: {'Horror'}, // psychological horror
  12377: {'Horror'}, // zombie
  3133: {'Horror'}, // vampire
  161791: {'Science Fiction'}, // kaiju
  // Crime/Mystery crossovers.
  207268: {'Crime', 'Mystery'}, // neo-noir
  10051: {'Crime'}, // heist
  10714: {'Crime', 'Thriller'}, // serial killer
  // Sci-fi flavours.
  12190: {'Science Fiction'}, // cyberpunk
  4379: {'Science Fiction'}, // time travel
  371846: {'Science Fiction'}, // artificial intelligence
  4563: {'Science Fiction'}, // virtual reality
  // Action flavours.
  779: {'Action'}, // martial arts
  780: {'Action'}, // kung fu
  // Musical.
  4344: {'Music'}, // musical
};

/// Returns a genre list combining [currentGenres] with any extras implied
/// by [keywordIds] per [kKeywordToExtraGenres]. Order is preserved
/// (existing genres first, then new ones in keyword-iteration order) and
/// duplicates are dropped.
///
/// Unknown keyword ids are silently skipped — TMDB adds new keywords
/// regularly and we only care about the subset we've mapped.
List<String> augmentGenresWithKeywords(
  Iterable<String> currentGenres,
  Iterable<int> keywordIds,
) {
  final seen = <String>{};
  final out = <String>[];
  for (final g in currentGenres) {
    if (g.isEmpty) continue;
    if (seen.add(g)) out.add(g);
  }
  for (final id in keywordIds) {
    final extras = kKeywordToExtraGenres[id];
    if (extras == null) continue;
    for (final g in extras) {
      if (seen.add(g)) out.add(g);
    }
  }
  return out;
}
