// GENERATED by scripts/generate_onboarding_seeds.py — do not edit.
// Curated list of 15 titles shown on first-run onboarding so the taste
// engine has something to score against on the new household's first Home open.

class OnboardingSeed {
  final int tmdbId;
  final String mediaType; // 'movie' | 'tv'
  final String title;
  final int year;
  final List<String> genres;
  final String posterPath;

  const OnboardingSeed({
    required this.tmdbId,
    required this.mediaType,
    required this.title,
    required this.year,
    required this.genres,
    required this.posterPath,
  });
}

const kOnboardingSeeds = <OnboardingSeed>[
  OnboardingSeed(
    tmdbId: 238,
    mediaType: 'movie',
    title: 'The Godfather',
    year: 1972,
    genres: ['Drama', 'Crime'],
    posterPath: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  ),
  OnboardingSeed(
    tmdbId: 680,
    mediaType: 'movie',
    title: 'Pulp Fiction',
    year: 1994,
    genres: ['Thriller', 'Crime', 'Comedy'],
    posterPath: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  ),
  OnboardingSeed(
    tmdbId: 155,
    mediaType: 'movie',
    title: 'The Dark Knight',
    year: 2008,
    genres: ['Action', 'Crime', 'Thriller'],
    posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  ),
  OnboardingSeed(
    tmdbId: 27205,
    mediaType: 'movie',
    title: 'Inception',
    year: 2010,
    genres: ['Action', 'Science Fiction', 'Adventure'],
    posterPath: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
  ),
  OnboardingSeed(
    tmdbId: 496243,
    mediaType: 'movie',
    title: 'Parasite',
    year: 2019,
    genres: ['Comedy', 'Thriller', 'Drama'],
    posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  ),
  OnboardingSeed(
    tmdbId: 545611,
    mediaType: 'movie',
    title: 'Everything Everywhere All at Once',
    year: 2022,
    genres: ['Action', 'Adventure', 'Science Fiction'],
    posterPath: '/u68AjlvlutfEIcpmbYpKcdi09ut.jpg',
  ),
  OnboardingSeed(
    tmdbId: 120467,
    mediaType: 'movie',
    title: 'The Grand Budapest Hotel',
    year: 2014,
    genres: ['Comedy', 'Drama'],
    posterPath: '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
  ),
  OnboardingSeed(
    tmdbId: 13,
    mediaType: 'movie',
    title: 'Forrest Gump',
    year: 1994,
    genres: ['Comedy', 'Drama', 'Romance'],
    posterPath: '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
  ),
  OnboardingSeed(
    tmdbId: 639,
    mediaType: 'movie',
    title: 'When Harry Met Sally...',
    year: 1989,
    genres: ['Comedy', 'Romance', 'Drama'],
    posterPath: '/rFOiFUhTMtDetqCGClC9PIgnC1P.jpg',
  ),
  OnboardingSeed(
    tmdbId: 313369,
    mediaType: 'movie',
    title: 'La La Land',
    year: 2016,
    genres: ['Comedy', 'Drama', 'Romance'],
    posterPath: '/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
  ),
  OnboardingSeed(
    tmdbId: 546554,
    mediaType: 'movie',
    title: 'Knives Out',
    year: 2019,
    genres: ['Comedy', 'Crime', 'Mystery'],
    posterPath: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
  ),
  OnboardingSeed(
    tmdbId: 1396,
    mediaType: 'tv',
    title: 'Breaking Bad',
    year: 2008,
    genres: ['Drama', 'Crime'],
    posterPath: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
  ),
  OnboardingSeed(
    tmdbId: 2316,
    mediaType: 'tv',
    title: 'The Office',
    year: 2005,
    genres: ['Comedy'],
    posterPath: '/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
  ),
  OnboardingSeed(
    tmdbId: 76331,
    mediaType: 'tv',
    title: 'Succession',
    year: 2018,
    genres: ['Drama', 'Comedy'],
    posterPath: '/z0XiwdrCQ9yVIr4O0pxzaAYRxdW.jpg',
  ),
  OnboardingSeed(
    tmdbId: 66732,
    mediaType: 'tv',
    title: 'Stranger Things',
    year: 2016,
    genres: ['Sci-Fi & Fantasy', 'Mystery', 'Action & Adventure'],
    posterPath: '/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
  ),
];
