#!/usr/bin/env python3
"""
Resolves TMDB keyword names → ids and emits entries for
lib/utils/keyword_genre_augment.dart's kKeywordToExtraGenres map.

Why: the augmenter widens a title's genre set using TMDB keyword ids, but
TMDB keyword ids aren't documented in bulk and change occasionally. This
script takes a hand-curated seed list (keyword_name, [extra_genres]),
queries /search/keyword for each name, picks the best exact match, and
prints a ready-to-paste Dart snippet.

Run once (or whenever you add new seeds):

    TMDB_API_KEY=... python3 scripts/generate_keyword_genre_map.py

Paste the printed entries into kKeywordToExtraGenres and re-run
`flutter test test/utils/keyword_genre_augment_test.dart` to make sure
nothing regresses.

Picking good seeds:
  - The keyword must reliably imply the genre — "cyberpunk" → Sci-Fi is
    solid; "dark" → Horror is noise.
  - Prefer compound / specific keywords ("space marines", "neo-noir")
    over broad ones ("fight", "family").
  - A keyword can map to ≥1 genre. "space western" → {Western, Science
    Fiction} is the whole point of this file.

The augmenter is **additive only** — it never removes canonical genres.
So false-positive genre additions are cheap; false-negative omissions
just mean a title stays un-widened (same as before).
"""

import json
import os
import sys
import time
import urllib.parse
import urllib.request

# (keyword_name, [extra_genre_names]).
# Genre names must match utils/tmdb_genres.dart exactly (case-sensitive).
# Movie genres: Action, Adventure, Animation, Comedy, Crime, Documentary,
# Drama, Family, Fantasy, History, Horror, Music, Mystery, Romance,
# Science Fiction, Thriller, War, Western.
# TV-only: Action & Adventure, Kids, News, Reality, Sci-Fi & Fantasy,
# Soap, Talk, War & Politics. The augmenter runs post-name-resolution so
# movie-domain names also cover the TV augment path (TV titles tagged
# 'Sci-Fi & Fantasy' on TMDB aren't missed — we just widen with the
# movie-shaped 'Science Fiction' name which is what the filter UI uses).
SEEDS: list[tuple[str, list[str]]] = [
    # --- Cross-genre sci-fi/war (the Sci-Fi + War zero-result problem) ---
    ("space marines", ["Science Fiction", "War"]),
    ("alien invasion", ["Science Fiction", "War"]),
    ("space battle", ["Science Fiction", "War"]),
    ("interstellar war", ["Science Fiction", "War"]),
    ("space opera", ["Science Fiction"]),
    # --- Western crossovers ---
    ("space western", ["Science Fiction", "Western"]),
    ("neo-western", ["Western"]),
    # --- Horror subgenres ---
    ("slasher", ["Horror"]),
    ("found footage", ["Horror"]),
    ("cosmic horror", ["Horror", "Science Fiction"]),
    ("body horror", ["Horror"]),
    ("psychological horror", ["Horror"]),
    ("zombie", ["Horror"]),
    ("vampire", ["Horror"]),
    ("kaiju", ["Science Fiction"]),
    # --- Crime/Mystery crossovers ---
    ("neo-noir", ["Crime", "Mystery"]),
    ("heist", ["Crime"]),
    ("serial killer", ["Crime", "Thriller"]),
    # --- Sci-fi flavours ---
    ("cyberpunk", ["Science Fiction"]),
    ("time travel", ["Science Fiction"]),
    ("artificial intelligence", ["Science Fiction"]),
    ("virtual reality", ["Science Fiction"]),
    # --- Action flavours ---
    ("martial arts", ["Action"]),
    ("kung fu", ["Action"]),
    # --- Musical ---
    ("musical", ["Music"]),
]

TMDB_BASE = "https://api.themoviedb.org/3"


def search_keyword(name: str, api_key: str) -> list[dict]:
    url = (
        f"{TMDB_BASE}/search/keyword?"
        f"api_key={api_key}&query={urllib.parse.quote(name)}"
    )
    with urllib.request.urlopen(url, timeout=15) as res:
        return json.load(res).get("results", [])


def pick_match(name: str, results: list[dict]) -> dict | None:
    """Exact-match wins; else first result."""
    if not results:
        return None
    lowered = name.lower()
    for r in results:
        if (r.get("name", "").lower()) == lowered:
            return r
    return results[0]


def main() -> int:
    api_key = os.environ.get("TMDB_API_KEY")
    if not api_key:
        print("error: set TMDB_API_KEY", file=sys.stderr)
        return 2

    print("// Generated by scripts/generate_keyword_genre_map.py. Paste these")
    print("// entries into lib/utils/keyword_genre_augment.dart's")
    print("// kKeywordToExtraGenres map.")
    print()

    misses: list[str] = []
    for name, genres in SEEDS:
        try:
            results = search_keyword(name, api_key)
        except Exception as e:
            print(f"// ERROR fetching {name!r}: {e}", file=sys.stderr)
            misses.append(name)
            continue

        match = pick_match(name, results)
        if match is None:
            print(f"// MISS {name!r} — no results")
            misses.append(name)
            continue

        resolved = match["name"]
        kid = match["id"]
        # Emit a Dart const-map entry like `9951: {'Science Fiction'}, // alien`
        body = ", ".join(f"'{g}'" for g in genres)
        suffix = f" (matched {resolved!r})" if resolved.lower() != name.lower() else ""
        print(f"  {kid}: {{{body}}}, // {name}{suffix}")
        time.sleep(0.04)  # Be polite; TMDB ratelimit is generous but not infinite.

    if misses:
        print("", file=sys.stderr)
        print(f"// {len(misses)} seed(s) unresolved:", file=sys.stderr)
        for n in misses:
            print(f"//   - {n}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
