#!/usr/bin/env python3
"""
One-shot: resolve a curated list of 15 onboarding seed titles into full
TMDB metadata and emit a Dart const for lib/utils/onboarding_seeds.dart.

These titles anchor the taste-profile engine's first impression of a new
household — they're deliberately spread across genres, eras, and formats
so a user's few ratings give the AI enough signal to start scoring.

Rerun whenever the curated list changes (rare).

    TMDB_API_KEY=... python3 scripts/generate_onboarding_seeds.py
"""

import json
import os
import sys
import time
import urllib.parse
import urllib.request

# (title, year, mediaType). Hand-picked mix — recent + classic, film + TV,
# drama + genre. Aim: 15 titles that most adults will have seen or heard
# of, spanning action, thriller, comedy, drama, romance, sci-fi, TV.
SEEDS = [
    ("The Godfather", 1972, "movie"),
    ("Pulp Fiction", 1994, "movie"),
    ("The Dark Knight", 2008, "movie"),
    ("Inception", 2010, "movie"),
    ("Parasite", 2019, "movie"),
    ("Everything Everywhere All at Once", 2022, "movie"),
    ("The Grand Budapest Hotel", 2014, "movie"),
    ("Forrest Gump", 1994, "movie"),
    ("When Harry Met Sally...", 1989, "movie"),
    ("La La Land", 2016, "movie"),
    ("Knives Out", 2019, "movie"),
    ("Breaking Bad", 2008, "tv"),
    ("The Office", 2005, "tv"),
    ("Succession", 2018, "tv"),
    ("Stranger Things", 2016, "tv"),
]


def tmdb_get(path, api_key, params=None):
    p = dict(params or {})
    p["api_key"] = api_key
    url = f"https://api.themoviedb.org/3{path}?{urllib.parse.urlencode(p)}"
    with urllib.request.urlopen(url, timeout=15) as r:
        return json.loads(r.read().decode())


def find(title, year, media_type, api_key):
    res = tmdb_get(f"/search/{media_type}", api_key, {"query": title})
    hits = res.get("results", [])
    exact = [h for h in hits
             if (h.get("title") or h.get("name") or "").lower() == title.lower()]
    pool = exact if exact else hits
    if not pool:
        return None

    def hit_year(h):
        d = h.get("release_date") or h.get("first_air_date") or ""
        return int(d[:4]) if len(d) >= 4 and d[:4].isdigit() else 0

    pool.sort(key=lambda h: (abs(hit_year(h) - year), -h.get("popularity", 0)))
    return pool[0]


def fetch_details(tmdb_id, media_type, api_key):
    return tmdb_get(f"/{media_type}/{tmdb_id}", api_key)


def main():
    api_key = os.environ.get("TMDB_API_KEY")
    if not api_key:
        print("TMDB_API_KEY env var required", file=sys.stderr)
        return 1

    out_rows = []
    for title, year, media_type in SEEDS:
        hit = find(title, year, media_type, api_key)
        if not hit:
            print(f"MISSING: {title}", file=sys.stderr)
            continue
        tmdb_id = hit["id"]
        details = fetch_details(tmdb_id, media_type, api_key)
        genre_names = [g["name"] for g in details.get("genres", [])]
        poster = details.get("poster_path") or ""
        title_out = details.get("title") or details.get("name") or title
        out_rows.append({
            "tmdb_id": tmdb_id,
            "media_type": media_type,
            "title": title_out,
            "year": year,
            "genres": genre_names,
            "poster_path": poster,
        })
        print(f"  {year}  {media_type}  {title_out}  (tmdb={tmdb_id})")
        time.sleep(0.05)

    out = []
    out.append("// GENERATED by scripts/generate_onboarding_seeds.py — do not edit.")
    out.append("// Curated list of 15 titles shown on first-run onboarding so the taste")
    out.append("// engine has something to score against on the new household's first Home open.")
    out.append("")
    out.append("class OnboardingSeed {")
    out.append("  final int tmdbId;")
    out.append("  final String mediaType; // 'movie' | 'tv'")
    out.append("  final String title;")
    out.append("  final int year;")
    out.append("  final List<String> genres;")
    out.append("  final String posterPath;")
    out.append("")
    out.append("  const OnboardingSeed({")
    out.append("    required this.tmdbId,")
    out.append("    required this.mediaType,")
    out.append("    required this.title,")
    out.append("    required this.year,")
    out.append("    required this.genres,")
    out.append("    required this.posterPath,")
    out.append("  });")
    out.append("}")
    out.append("")
    out.append("const kOnboardingSeeds = <OnboardingSeed>[")
    for r in out_rows:
        genres = ", ".join(f"'{g}'" for g in r["genres"])
        title_esc = r["title"].replace("'", r"\'")
        out.append("  OnboardingSeed(")
        out.append(f"    tmdbId: {r['tmdb_id']},")
        out.append(f"    mediaType: '{r['media_type']}',")
        out.append(f"    title: '{title_esc}',")
        out.append(f"    year: {r['year']},")
        out.append(f"    genres: [{genres}],")
        out.append(f"    posterPath: '{r['poster_path']}',")
        out.append("  ),")
    out.append("];")

    with open("lib/utils/onboarding_seeds.dart", "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"\nWrote {len(out_rows)} seeds to lib/utils/onboarding_seeds.dart")
    return 0


if __name__ == "__main__":
    sys.exit(main())
